all: simple_pipe connected-pipe multi_pipe
simple_pipe: simple_pipe.cc
	g++ simple_pipe.cc -o simple_pipe -g
connected-pipe: connected_pipe.cc
	g++ connected_pipe.cc -o connected_pipe -g
multi_pipe: multi_pipe.cc
	g++ multi_pipe.cc -o multi_pipe -g
clean:
	rm simple_pipe connected_pipe multi_pipe