#!/bin/bash
# 1. (1 points) Count how many lines are there in “data.dat”.
wc -l data.dat
# 2. (1 points) Count how many lines of those contain “dolor” or “dalor”?
grep -E "d(o|a)lor" data.dat | wc -l
# 3. (1 points) Count how many words are there in “data.dat”?
wc -w < data.dat
# 4. (1 points) Count how many of those start with “mol”?
grep -E "^mol" data.dat | wc -l